language: java
sudo: false
notifications:
  slack:
    secure: KTIBZUx5ECMZaFZISWaUYgB6vR86ieDKxgDKQlDkNDPUcR2qwNz6NxZUiMH+qPc7V12gLjZqO2RZmm4dZuOXzw6h8zPv7bzG1lVdL4mBA5ML/MSaJlZJIJN7e6UlVcAb+fBQWhEmUWimVM0aRnzFa8e37WYVBq+ZudRT1e2xQftdeVVQEpuk3tYTsPnfjqvNFh1OzRetNXI0Yo7HHGSAQXCtOh0PZnQWHBKmDHehA1TXEvuFZVmYEHyPH+YaHDQ3XzuqVWtfeT8k3EDCl5cJ1M590Hw82dUNfA+/Vvf8UprNrMc5VK3YWOBr8vlIi0T4g6050taVv9xLUJPwUylBY5W0RBktjjUxHl32MmaVdde3LLpYVLhvks0wATgsx6yV37sepIMLiyMHF+HXaeJTlohNYlb2ttTscfuhN2rlne+QvYvIekk+iDLBnbWZAspB6lvVxtWV4/xC9/Sj8yQO1E49z2zsgY7tClPBgMSyqdzbH3+CzsvV6SEw+hMEG3XYU5Y5o+9jXEriWpZUGwsXeuZNaPfNaEFDkINmcqx1IjQ/pLlCLg7hSs/3+JmuTtkXCiOP8j9eh9s/sEQKUNBECKwsn9sRBd6lpEOVaiKnMKGzHJ2EZUdEEXXYYhQeEpxf1WoTx2mCLiEFq4VlGbxFJiuJ1/Vb8cztYdDLbaBf3Po=
deploy:
  provider: releases
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_bracnhes: true
    tags: true
    repo: xebialabs-community/xlr-quickbuild-plugin
  api_key:
    secure: pHQR2YLEAA0uAvMYNQ/srMYGNOvdAbnPlnCVfO6tqtRgo15POPWlswPtBrx2/jGhyTO2tc1rZ3l5bDMd3vCA1Rhrd3qrOQEblD15aVo1P8svo4nzh4dPaR/Zr4NtkOEw7UzF9zeOV1xZOuY0RW6MAaUFmRcy/KCk9A2yZ4DSRJYvKETc1zJh7Ouat4Yq10hHyX9iEVv6/c9jo+HMxTWvVAXnNbjcLT/k/MmIqO8voQp4/Be1cyU29DkPwZwI6s+9ZutCeWA8/avGUsCwcPZR3/du+PGN98Anc5N6q8eZVZ7/5cZy6dhp2CHxE21u7N9tjsY1WjF2rUBhgGptsHSe2XwBZOPurzpOJHjzGXmCnYhj+5RT8mJZpOq8bRxv5Rq2Io0Qnp0v1IKZm0qbspfP7CY8Ny/5Bz+91SXJ5Kfk/sF3frnN7cwUNoq5xmSMTIS0cQ0jv4te7BkL/GIK2NC3EBE4xB0bEtnVB2y9wkXiHN5H+E24zUqDNr1M5kAe3QX/Xtbu4h68iR9l7UTvN4MLLcLHl7eGdA4VuItOULZXM2d326UrreTeyhSQpzHhgAJwEtmWLN2mrA1fQ0oLaJcez+5XqEx93jH6Pavdqa60zQ0a20msBKrlG+i8y6UMc27ZQnNNSGHWUYnKIIGo7rpLWAYdLCji7WpKrw81MfAfnNk=
