language: java
sudo: false
notifications:
  slack:
    secure: lAfKZMobnMs+89MlJ1hQIyr9imRI6C7PEV8fdqpRKcTCzaop5spreeXFHfa3jJ03LQS4rOMsqkAllU2Kmxdjt4YQyMylocxwwF3o/77/4pUE/CqTsKCfm8qnEjBEwQ+5i+Q40/W2dlNW1tFYlAW8F5lOe6IzCgQwl/4N1MOgn0QbqCaIyRIlZR1S/MgDpOB9BvmXhey3NWxuhuhVbNbxP4bvmyLh2b0AN53elR6HDCNAYKKUOA3eRI7tek1IHYCzE45gyGjP/ZN4NlJ2KXgclwfFj4M/xmcPfMt/ylN4Vvf63KQHGOZo+PyT3rSlOl9t4WlLihdxRAmk8KjXAXt/KrnaLbBzp5ABUS7mNSPc8uQuPTQCPjnt6We2iwvEZn1LXtEiNKZFXtbQwml0rUUCYPDv6uMQEbuw5xqoDb/a0TJXc8lFP0SRB0S4loRonl4l09u8y5MLrOEEi0XITNn36rDQLC8uhM2s9OJAlV06GLUin1PWjoUEJDsV1xMnKo4SNX2kvQGhHBRHBSpPcUVWzzaSBOcdxw6+3TBmlsNQpYx0uJXzGFrgz/wS1TPk3gKAehlfWXIhIr4Vx5TbESHXjHDGz3Ewi+ZSNUJWy12YZ3/ikzzzri4Ki9IlV/SjgoU450Bn4e5nCYMvR4m9jQmABTiUwA9g+oA5i9xAY97syKY=
deploy:
  provider: releases
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_bracnhes: true
    tags: true
    repo: xebialabs-community/xlr-quickbuild-plugin
  api_key:
    secure: fn+awkzD05PbZkp7gqlvaoOhHagk9JuUx+KD7SmsFwnynmFr6askWJAL4OhowFp5U1Y0DWuMiExmlh0f6NOrG37FNhjxefWYUMbJSc1wdzqIomKU9eHI4ZOav9cA86jYJo1UfUN0+nLmFKBQUzn+b0COv7zonq8+LuSDG1rJMxxg6eOFzx0YZMlJUHSbE7FsCINOHX8U4oA2L4khOpVThUqZ7Lc+cOV5THW7+Vt9cQ/I7MWJxqnRvpaGWmgNF3lHZftaYm9OUhbPmQym42OA/TJaCcuO8xXRKgKRCZB6uF9vz9XrFPFZxjD11pNGEPIkv4xfeIKWettfyA9bIZRa+G9eXD5F+2Mj1Y8BHNdxEzMdwfWCQqQARjkVSINvF0YLB76MzPX6uztcnGC8pld+wlKrKf01wE6dxQHe1X96PYDSG8Rqc1hM3crpa91apYem9JGTXvLk8XDiXP+qoX0T9IqVmC7XleY9I6evT0PlZ2/E8QbBMCKiwdlfq8u3PgpeIzN3qnOB3WNk06Sp9ZMP4BArI4hSTLyE5s7UlP3PBdmOVimlaJzT58gWfyRfYEGrNLU4YeVgh6dlgc6Yv9zD6ikKbmCY5Zudl+XYmD+3D1dmmlI43RKEagdoh2su1bblk+nOpXilpG/M5a4MUgh8a2Ecmky0y0y0XjEHstuSXDY=
