language: java
sudo: false
notifications:
  slack:
    secure: WzdS5sSSQziwbZwqW8nCddRGC8SSrgcPyVn9NbV2MOkqa4mFawQOL05CCOc0RfV7otCCqxsDqXAehuyKzEVA8VrQ1g10Eelppbnv9WxDYzIj1M2MPmyo4RzHK6+aw0KRIujufgYQdxit+N/J2xATnUy+3hiXBQprCnIGXYaNk2w=
  hipchat:
    rooms:
      secure: A0rtcc5iWVOiKodiYxX8DzNn777k2boUWILXtfEKKXqHzxENYaj5EHeMT+kC+2F/rnnjS79fMFD9VU4d/dbjiQH4wzHMPA5gBGpOpb+q0zbLTxt4sYmn+9HqVoIu774ZSBkX1fh5y/MM6qrjUJbPLMuBylM88PhYu95hGL7TW1w=
deploy:
  provider: releases
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_bracnhes: true
    tags: true
    repo: xebialabs-community/xlr-quickbuild-plugin
  api_key:
    secure: fn+awkzD05PbZkp7gqlvaoOhHagk9JuUx+KD7SmsFwnynmFr6askWJAL4OhowFp5U1Y0DWuMiExmlh0f6NOrG37FNhjxefWYUMbJSc1wdzqIomKU9eHI4ZOav9cA86jYJo1UfUN0+nLmFKBQUzn+b0COv7zonq8+LuSDG1rJMxxg6eOFzx0YZMlJUHSbE7FsCINOHX8U4oA2L4khOpVThUqZ7Lc+cOV5THW7+Vt9cQ/I7MWJxqnRvpaGWmgNF3lHZftaYm9OUhbPmQym42OA/TJaCcuO8xXRKgKRCZB6uF9vz9XrFPFZxjD11pNGEPIkv4xfeIKWettfyA9bIZRa+G9eXD5F+2Mj1Y8BHNdxEzMdwfWCQqQARjkVSINvF0YLB76MzPX6uztcnGC8pld+wlKrKf01wE6dxQHe1X96PYDSG8Rqc1hM3crpa91apYem9JGTXvLk8XDiXP+qoX0T9IqVmC7XleY9I6evT0PlZ2/E8QbBMCKiwdlfq8u3PgpeIzN3qnOB3WNk06Sp9ZMP4BArI4hSTLyE5s7UlP3PBdmOVimlaJzT58gWfyRfYEGrNLU4YeVgh6dlgc6Yv9zD6ikKbmCY5Zudl+XYmD+3D1dmmlI43RKEagdoh2su1bblk+nOpXilpG/M5a4MUgh8a2Ecmky0y0y0XjEHstuSXDY=
